name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: |
          dotnet restore ./UsersService/UsersService.csproj
          dotnet restore ./PostsService/PostsService.csproj
          dotnet restore ./DeliveryService/DeliveryService.csproj
          dotnet restore ./ApiGateway/ApiGateway.csproj

      - name: Build
        run: |
          dotnet build ./UsersService/UsersService.csproj --configuration Release --no-restore
          dotnet build ./PostsService/PostsService.csproj --configuration Release --no-restore
          dotnet build ./DeliveryService/DeliveryService.csproj --configuration Release --no-restore
          dotnet build ./ApiGateway/ApiGateway.csproj --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test ./UsersService/UsersService.csproj --no-build --verbosity normal
          dotnet test ./PostsService/PostsService.csproj --no-build --verbosity normal
          dotnet test ./DeliveryService/DeliveryService.csproj --no-build --verbosity normal
          dotnet test ./ApiGateway/ApiGateway.csproj --no-build --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_IVAN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push users-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./UsersService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IVAN }}/users-service:latest

      - name: Build and push posts-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./PostsService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IVAN }}/posts-service:latest

      - name: Build and push delivery-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./DeliveryService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IVAN }}/delivery-service:latest

      - name: Build and push apigateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ApiGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IVAN }}/apigateway:latest
